FROM maven:3.8.6-openjdk-8

WORKDIR /app

# Copy JAR file and configuration files
COPY target/satd-analyzer-jar-with-all-dependencies.jar .
COPY repos.txt .
COPY mySQL.properties .
COPY lib/ lib/
COPY entrypoint.sh .

# Update MySQL host to connect from container to host machine
RUN sed -i 's/URL=localhost/URL=host.docker.internal/' mySQL.properties
RUN chmod +x entrypoint.sh

# Run the analysis with DebtHunter detector
ENTRYPOINT ["./entrypoint.sh"]

